secrets: secrets.yml

templates:
  transmission series:
    transmission:
      host: 192.168.253.52
      port: 9091
      username: '{{ secrets.tr.usr }}'
      password: '{{ secrets.tr.pwd }}'
      path: '{{ secrets.tr.root }}'
    set:
      path: '{{ secrets.tr.root }}/{{ series_name }}'
      label: 'FlexGet series - {{ series_name }}'

  ongoings:
    include: series.yml
    thetvdb_lookup: yes
    digest: daily email

  fix quality:
    if:
      - "not quality":
          set:
            quality: 720p


  horrible quality:
    if:
      - "all(['HorribleSubs' in title,'1080p' in quality])":
          set:
            quality: 480p
      - "all(['HorribleSubs' in title,'720p' in quality])":
          set:
            quality: 576p

tasks:
  fetch nyaa:
    priority: 2
    template:
      - ongoings
      - fix quality
      - transmission series
    rss:
      url: 'http://www.nyaa.se/?page=rss&cats=1_37&term=mkv+-horriblesubs+-1080p+-480p+-dvdrip+-%22bd%22&filter=2'
      all_entries: no

  fetch horrible:
    priority: 5
    template:
      - ongoings
      - horrible quality
      - transmission series
    rss:
      url: 'http://www.nyaa.se/?page=rss&cats=1_37&term=mkv+horriblesubs+-1080p+-480p&filter=2'
      all_entries: no

  discover nyaa:
    priority: 10
    template:
      - ongoings
      - horrible quality
      - fix quality
      - transmission series
    discover:
      what:
        - emit_series:
            from_start: yes
            backfill: yes
      from:
        - nyaa:
            category: anime eng
            filter: trusted only

  mail digest:
    priority: 20
    emit_digest:
      list: daily email
    seen: local
    accept_all: yes

    email:
      from: '{{ secrets.mail.user }}'
      to: '{{ secrets.mail.to }}'
      smtp_host: 'smtp.mailgun.com'
      smtp_login: true
      smtp_username: '{{ secrets.mail.user }}'
      smtp_password: '{{ secrets.mail.pass }}'
      smtp_tls: true
      template: 'series.template'

schedules:
  - tasks: [fetch nyaa, fetch horrible]
    interval:
      minutes: 30

  - tasks: mail digest
    interval:
      hours: 1

  - tasks: discover nyaa
    interval:
      hours: 8
