variables: secrets.yml

templates:
  transmission series:
    transmission:
      host: 192.168.253.52
      port: 9091
      username: '{? tr.usr ?}'
      password: '{? tr.pwd ?}'
      path: '{{ secrets.tr.root }}'
    set:
      path: '{? tr.root ?}/{{ series_name }}'
      label: 'FlexGet series - {{ series_name }}'
    pathscrub: windows

  ongoings:
    configure_series:
      settings:
        identified_by: sequence
        upgrade: yes
        timeframe: 6 minutes
        target: 720p
        qualities:
          - 576p
          - 720p
        tracking: backfill
        begin: 1
      from:
        my_anime_list:
          username: '{? mal.username ?}'
          status:
            - watching
            - plan_to_watch
        csv:
          url: https://raw.githubusercontent.com/LynxyssCZ/flexget-atfb/master/const/aliases.csv
          values:
            title: 1
            configure_series_alternate_name: 2
            url: 3
    thetvdb_lookup: yes
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'

  fix quality:
    if:
      - "not quality":
          set:
            quality: 720p


  horrible quality:
    if:
      - "all(['HorribleSubs' in title,'1080p' in quality])":
          set:
            quality: 480p
      - "all(['HorribleSubs' in title,'720p' in quality])":
          set:
            quality: 576p
      - "all(['BakedFish' in title,'720p' in quality])":
          set:
            quality: 576p
      - "all(['BakedFish' in title,'1080p' in quality])":
          set:
            quality: 480p

tasks:
  fetch tt:
    priority: 2
    template:
      - ongoings
      - fix quality
      - transmission series
    rss:
      url: 'https://www.tokyotosho.info/rss.php?filter=1'
      all_entries: yes

  fetch horrible:
    priority: 5
    template:
      - ongoings
      - horrible quality
      - transmission series
    seen_info_hash: no
    rss:
      url: 'http://horriblesubs.info/rss.php?res=720'
      all_entries: yes

  discover:
    priority: 10
    template:
      - ongoings
      - horrible quality
      - fix quality
      - transmission series
    discover:
      release_estimations: ignore
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - nyaa:
            category: anime eng
            filter: trusted only

schedules:
  - tasks: [fetch tt, fetch horrible]
    interval:
      minutes: 30

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes
